- name: Delete Path
  hosts: '{{ HOST }}'
  gather_facts: False
  remote_user: '{{ REMOTE_USER }}'
  become: '{{ EXECUTE_AS_SUDO }}'
  become_method: sudo
  connection: '{{ CONNECTION }}'
  tasks:
    - name: Delete path
      file: path='{{ PATH }}' state=absent
