- name: Fetch directories
  hosts: '{{ HOST }}'
  gather_facts: False
  remote_user: '{{ REMOTE_USER }}'
  become: '{{ EXECUTE_AS_SUDO }}'
  become_method: sudo
  tasks:
    - name: Bundle directory
      command: tar cvf '{{ DST_PATH }}' '{{ SRC_PATH }}'

    - name: Copy operation
      fetch: src=/tmp/compressed.tar dest='{{ DST_PATH }}'
