- name: Move files and directories
  hosts: '{{ HOST }}'
  gather_facts: False
  remote_user: '{{ REMOTE_USER }}'
  become: '{{ EXECUTE_AS_SUDO }}'
  become_method: sudo
  connection: '{{ CONNECTION }}'
  tasks:
    - name: Move operation
      command: mv '{{ SRC_PATH }}' '{{ DST_PATH }}'
