- name: Move to files and directories to server
  hosts: '{{ HOST }}'
  gather_facts: False
  remote_user: '{{ REMOTE_USER }}'
  become: '{{ EXECUTE_AS_SUDO }}'
  become_method: sudo
  tasks:
    - name: Move to Remote HOST
      copy: src='{{ SRC_PATH }}'  dest='{{ DST_PATH }}'
